# Generated by Django 6.0.4 on 2026-05-08 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. ADEMEBA Valles CHUPON', max_length=150)),
                ('rama', models.CharField(choices=[('Varonil', 'Varonil (Masculino)'), ('Femenil', 'Femenil (Femenino)'), ('Mixta', 'Rama Mixta (Ambos géneros)')], default='Mixta', max_length=50)),
                ('anio_nac_min', models.IntegerField(default=2008, help_text='Año de nacimiento más antiguo permitido (Ej. 2008)')),
                ('anio_nac_max', models.IntegerField(default=2020, help_text='Año de nacimiento más reciente permitido (Ej. 2020)')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('costo_inscripcion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de guerra (Ej. Abejitas)', max_length=100)),
                ('club', models.CharField(help_text='Nombre formal (Ej. Club Cedees)', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('entrenador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_entrenado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adeudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adeudos', to='gestion.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('rama', models.CharField(choices=[('Varonil', 'Varonil'), ('Femenil', 'Femenil')], max_length=50)),
                ('region', models.CharField(choices=[('Valles Centrales', 'Valles Centrales'), ('Istmo', 'Istmo'), ('Papaloapan', 'Papaloapan'), ('Sierra Sur', 'Sierra Sur'), ('Sierra Norte', 'Sierra Norte'), ('Costa', 'Costa'), ('Cañada', 'Cañada'), ('Mixteca', 'Mixteca')], max_length=100)),
                ('municipio_vive', models.CharField(default='Sin especificar', max_length=200)),
                ('posicion', models.CharField(choices=[('Base (1)', 'Base (1)'), ('Escolta (2)', 'Escolta (2)'), ('Alero (3)', 'Alero (3)'), ('Ala-Pívot (4)', 'Ala-Pívot (4)'), ('Pívot (5)', 'Pívot (5)'), ('Sin definir', 'Sin definir')], default='Sin definir', max_length=20)),
                ('numero_camiseta', models.CharField(blank=True, max_length=3, null=True)),
                ('tipo_sangre', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10)),
                ('telefono_credencial', models.CharField(max_length=20)),
                ('foto_perfil', models.ImageField(upload_to='fotos/')),
                ('archivo_curp', models.FileField(upload_to='documentos/')),
                ('archivo_identificacion', models.FileField(upload_to='documentos/')),
                ('acta_nacimiento', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('credencial_escolar', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('archivo_afiliacion', models.FileField(blank=True, null=True, upload_to='afiliaciones/')),
                ('validado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('numero_afiliacion', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.equipo')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_equipos', to='gestion.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='MiembroStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('Asistente', 'Asistente de Entrenador'), ('Preparador Físico', 'Preparador Físico'), ('Médico', 'Médico / Fisioterapeuta'), ('Estadístico', 'Estadístico'), ('Delegado', 'Delegado de Equipo')], max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='staff_fotos/')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_staff', to='gestion.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono principal del responsable.', max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles_tutores/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Falta Tecnica', 'Falta Técnica (Acumulación)'), ('Falta Antideportiva', 'Falta Antideportiva'), ('Expulsion', 'Expulsión del Partido'), ('Administrativa', 'Sanción Administrativa')], max_length=50)),
                ('motivo', models.TextField()),
                ('juegos_suspension', models.IntegerField(default=1)),
                ('juegos_cumplidos', models.IntegerField(default=0)),
                ('fecha_sancion', models.DateField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanciones_entrenador', to=settings.AUTH_USER_MODEL)),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='gestion.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='gestion.temporada')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(help_text='Ej. Jornada 1, Semifinal, Final', max_length=50)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('cancha', models.CharField(blank=True, help_text='Lugar del encuentro', max_length=150, null=True)),
                ('puntos_local', models.IntegerField(default=0)),
                ('puntos_visitante', models.IntegerField(default=0)),
                ('jugado', models.BooleanField(default=False, help_text='Marca esta casilla cuando el partido termine')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='gestion.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='gestion.equipo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='gestion.temporada')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos_jugados', to='gestion.equipo')),
                ('jugadores', models.ManyToManyField(blank=True, related_name='torneos_participados', to='gestion.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='gestion.temporada')),
            ],
            options={
                'unique_together': {('temporada', 'equipo')},
            },
        ),
    ]
