# Generated by Django 6.0.4 on 2026-05-10 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripciontorneo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='perfiltutor',
            name='foto',
        ),
        migrations.AddField(
            model_name='jugador',
            name='archivo_pago',
            field=models.FileField(blank=True, null=True, upload_to='jugadores/pagos/'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='estado_validacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado por Corrección')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='jugador',
            name='intentos_registro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.equipo'),
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='club',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/logos/'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='motivo',
            field=models.CharField(default='Ingreso', max_length=100),
        ),
        migrations.AlterField(
            model_name='inscripciontorneo',
            name='jugadores',
            field=models.ManyToManyField(related_name='torneos_participados', to='gestion.jugador'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='acta_nacimiento',
            field=models.FileField(default='', upload_to='jugadores/actas/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='archivo_afiliacion',
            field=models.FileField(default='', upload_to='jugadores/afiliacion/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='archivo_curp',
            field=models.FileField(upload_to='jugadores/curp/'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='archivo_identificacion',
            field=models.FileField(upload_to='jugadores/id/'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='codigo_qr',
            field=models.ImageField(blank=True, default='', upload_to='jugadores/qrs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='credencial_escolar',
            field=models.FileField(default='', upload_to='jugadores/escolar/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='foto_perfil',
            field=models.ImageField(upload_to='jugadores/fotos/'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='municipio_vive',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='numero_afiliacion',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('Base', 'Base'), ('Escolta', 'Escolta'), ('Alero', 'Alero'), ('Ala-Pívot', 'Ala-Pívot'), ('Pívot', 'Pívot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='rama',
            field=models.CharField(choices=[('Varonil', 'Varonil'), ('Femenil', 'Femenil')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='region',
            field=models.CharField(choices=[('Valles Centrales', 'Valles Centrales'), ('Istmo', 'Istmo'), ('Papaloapan', 'Papaloapan'), ('Sierra Sur', 'Sierra Sur'), ('Sierra Norte', 'Sierra Norte'), ('Costa', 'Costa'), ('Cañada', 'Cañada'), ('Mixteca', 'Mixteca')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='telefono_credencial',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='tipo_sangre',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='miembrostaff',
            name='cargo',
            field=models.CharField(choices=[('Asistente', 'Asistente'), ('Prep. Físico', 'Prep. Físico'), ('Médico', 'Médico'), ('Delegado', 'Delegado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='miembrostaff',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='staff/'),
        ),
        migrations.AlterField(
            model_name='miembrostaff',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='cancha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='jornada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='jugado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfiltutor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='fecha_sancion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='juegos_suspension',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.jugador'),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.temporada'),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='tipo',
            field=models.CharField(choices=[('Técnica', 'Falta Técnica'), ('Antideportiva', 'Falta Antideportiva'), ('Expulsión', 'Expulsión'), ('Suspensión LGE', 'Suspensión por Liga')], max_length=50),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='anio_nac_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='anio_nac_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='costo_inscripcion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='rama',
            field=models.CharField(choices=[('Varonil', 'Varonil'), ('Femenil', 'Femenil'), ('Mixta', 'Mixta')], default='Mixta', max_length=10),
        ),
    ]
