# Generated by Django 6.0.4 on 2026-05-10 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_inscripciontorneo_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='equipo_solicitado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_de_ingreso', to='gestion.equipo'),
        ),
    ]
