# Generated by Django 6.0.4 on 2026-05-17 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_jugador_equipo_solicitado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adeudo',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adeudos_tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialequipo',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miembrostaff',
            name='folio_afiliacion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.equipo'),
        ),
        migrations.AlterField(
            model_name='miembrostaff',
            name='cargo',
            field=models.CharField(choices=[('Entrenador Principal', 'Entrenador Principal'), ('Asistente 1', 'Asistente 1'), ('Asistente 2', 'Asistente 2'), ('Asistente 3', 'Asistente 3'), ('Prep. Físico', 'Prep. Físico'), ('Médico', 'Médico'), ('Delegado', 'Delegado')], max_length=30),
        ),
        migrations.CreateModel(
            name='SolicitudCambioEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('equipo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_solicitados', to='gestion.equipo')),
                ('equipo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salidas_solicitadas', to='gestion.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to='gestion.jugador')),
            ],
        ),
    ]
