# Generated by Django 6.0.4 on 2026-05-23 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_adeudo_tutor_historialequipo_fecha_salida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adeudo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('REVISION', 'En Revisión (Voucher Enviado)'), ('PAGADO', 'Liquidado / Pagado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='adeudo',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adeudos_jugador', to='gestion.jugador'),
        ),
        migrations.AddField(
            model_name='adeudo',
            name='temporada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adeudos_temporada', to='gestion.temporada'),
        ),
        migrations.AddField(
            model_name='adeudo',
            name='tipo_adeudo',
            field=models.CharField(choices=[('INSCRIPCION', 'Inscripción a Torneo'), ('CREDENTIAL', 'Credenciales / Trámites'), ('MULTA', 'Multas / Disciplina'), ('ARBITRAJE', 'Arbitraje')], default='INSCRIPCION', max_length=20),
        ),
        migrations.AddField(
            model_name='adeudo',
            name='voucher_comprobante',
            field=models.FileField(blank=True, null=True, upload_to='vouchers_finanzas/'),
        ),
    ]
