# Generated by Django 6.0.4 on 2026-05-26 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_adeudo_estado_adeudo_jugador_adeudo_temporada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='campeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campeonatos', to='gestion.equipo'),
        ),
    ]
