# Generated by Django 6.0.4 on 2026-05-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_temporada_campeon'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciontorneo',
            name='validada',
            field=models.BooleanField(default=False),
        ),
    ]
