# Generated by Django 6.0.4 on 2026-06-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_inscripciontorneo_validada'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='max_jugadores_roster',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='temporada',
            name='min_jugadores_roster',
            field=models.IntegerField(default=8),
        ),
    ]
