# Generated by Django 6.0.4 on 2026-06-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_temporada_max_jugadores_roster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='max_jugadores',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='equipo',
            name='rama',
            field=models.CharField(choices=[('Varonil', 'Varonil'), ('Femenil', 'Femenil'), ('Mixta', 'Mixta')], default='Mixta', max_length=10),
        ),
        migrations.AddField(
            model_name='temporada',
            name='dias_tolerancia_pago',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='temporada',
            name='inscripciones_abiertas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
