# Generated by Django 6.0.1 on 2026-06-15 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_equipo_categoria_equipo_max_jugadores_equipo_rama_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscripciones_abiertas', models.BooleanField(default=False, verbose_name='Inscripciones globales abiertas')),
                ('fecha_inicio_inscripciones', models.DateField(blank=True, null=True, verbose_name='Fecha inicio inscripciones')),
                ('fecha_fin_inscripciones', models.DateField(blank=True, null=True, verbose_name='Fecha fin inscripciones')),
                ('monto_sancion_default', models.DecimalField(decimal_places=2, default=250.0, max_digits=8, verbose_name='Monto multa por defecto')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.AddField(
            model_name='adeudo',
            name='sancion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adeudos', to='gestion.sancion'),
        ),
        migrations.AddField(
            model_name='sancion',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sancion',
            name='monto_multa',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='sancion',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SolicitudCambioContrasena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('contrasena_temporal', models.CharField(blank=True, max_length=128, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_contrasena', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Contraseña',
                'verbose_name_plural': 'Solicitudes de Cambio de Contraseña',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
