# Generated by Django 6.0.1 on 2026-06-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_configuracionsistema_adeudo_sancion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcambiocontrasena',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo'),
        ),
    ]
