# Generated by Django 6.0.4 on 2026-06-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_solicitudcambiocontrasena_motivo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeudo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('REVISION', 'En Revisión (Voucher Enviado)'), ('PAGADO', 'Liquidado / Pagado')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='pagado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='tipo_adeudo',
            field=models.CharField(choices=[('INSCRIPCION', 'Inscripción a Torneo'), ('CREDENTIAL', 'Credenciales / Trámites'), ('MULTA', 'Multas / Disciplina'), ('ARBITRAJE', 'Arbitraje')], db_index=True, default='INSCRIPCION', max_length=20),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='estado_validacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado por Corrección')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='rama',
            field=models.CharField(choices=[('Varonil', 'Varonil'), ('Femenil', 'Femenil')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='validado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='partido',
            name='jugado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='activa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='solicitudcambioequipo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='PENDIENTE', max_length=20),
        ),
    ]
