# Generated by Django 6.0.1 on 2026-06-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_adeudo_estado_alter_adeudo_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='region',
            field=models.CharField(choices=[('Valles Centrales', 'Valles Centrales'), ('Istmo', 'Istmo'), ('Papaloapan', 'Papaloapan'), ('Sierra Sur', 'Sierra Sur'), ('Sierra Norte', 'Sierra Norte'), ('Costa', 'Costa'), ('Cañada', 'Cañada'), ('Mixteca', 'Mixteca'), ('Cualquier Región', 'Cualquier Región')], default='Cualquier Región', max_length=50),
        ),
    ]
