# Generated by Django 6.0.4 on 2026-06-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_perfilentrenador'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripciontorneo',
            unique_together={('temporada', 'equipo')},
        ),
    ]
