# Generated by Django 6.0.4 on 2026-06-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_alter_inscripciontorneo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembrostaff',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
