# Generated by Django 6.0.4 on 2026-06-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_miembrostaff_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilentrenador',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='perfilentrenador',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
