# Generated by Django 6.0.1 on 2026-06-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_perfilentrenador_curp_perfilentrenador_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del banco'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='costo_inscripcion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Costo de inscripción general'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='nombre_cuenta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titular de la cuenta'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de cuenta bancaria'),
        ),
        migrations.AddField(
            model_name='miembrostaff',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='perfilentrenador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
