# Generated by Django 6.0.1 on 2026-07-01 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_configuracionsistema_banco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('numero_cuenta', models.CharField(max_length=30, verbose_name='Número de cuenta / CLABE')),
                ('titular', models.CharField(max_length=200, verbose_name='Nombre del titular')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Monto a reembolsar')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False, verbose_name='Reembolso procesado')),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('adeudo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos', to='gestion.adeudo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reembolsos', to='gestion.jugador')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reembolso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Reembolso',
                'verbose_name_plural': 'Solicitudes de Reembolso',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
