# Generated by Django 6.0.1 on 2026-07-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_reembolso'),
    ]

    operations = [
        migrations.AddField(
            model_name='adeudo',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo del voucher'),
        ),
    ]
